version: '3.5'

services:
  sqldb:
    image: postgres:12.3-alpine
    network_mode: bridge
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=gallery-iiitb_production
      - POSTGRES_USER=gallery-iiitb
      - POSTGRES_PASSWORD=${IIITBG_PG_PASS}

  web:
    build: .
    network_mode: bridge
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - sqldb
    links:
      - sqldb:sqldb

volumes:
  postgres_data:
